-- creating tables

CREATE TABLE IF NOT EXISTS  Clients (Id INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(25) NOT NULL);
CREATE TABLE IF NOT EXISTS Graphs (Id INT PRIMARY KEY AUTO_INCREMENT, Clients_Id INT);
CREATE TABLE IF NOT EXISTS Nodes (Id INT PRIMARY KEY AUTO_INCREMENT, Graphs_id INT, X_Coord INT, Y_Coord INT, Paths_Id INT, Routes_Index INT);
CREATE TABLE IF NOT EXISTS Edges (Id INT PRIMARY KEY AUTO_INCREMENT, Source_Node_id INT, Destination_Node_Id INT, Distance INT);
CREATE TABLE IF NOT EXISTS Paths (Id INT PRIMARY KEY AUTO_INCREMENT, Source_Node_id INT, Target_Node_id INT, Distance INT, Graphs_id INT);
